### ISSUE TITLE
Double click is required to open Google Auth on without-modal demo

### ISSUE THREAD

**Issue by rjborba** [Web3Auth/web3auth-wagmi-connector#42] opened 2023-02-04 19:33 UTC
Hey guys! First of all thanks for this connector. It helped a lot to understand web3auth integration with rainbowkit.

But I would like to request some help. On the example app demo-without-modal, everything works just nine, but when you try it on Safari Mobile it is required two touchs to actually start the auth process with google. It do not happen on Desktop or when Metamask, for example, is picked on mobile as well.

It is a silly thing, but it is driving me crazy. Does anyone noticed it?

Also, it is import to say that it do not happen on Chrome Mobile. 

Thanks!

**Comment by yashovardhan** [comment] 2023-04-13 03:17
Can you try this in `3.0.1` please?

**Comment by zobeirhamid** [comment] 2023-04-17 17:09
I am facing the same problem while using `3.0.1.`. 
Here is a video:

https://user-images.githubusercontent.com/20030709/232559305-ba39257a-2eaa-411d-b03c-c8a1297d9c9b.mov


I am pretty sure this is because there is a delay between the user interaction and the actual opening of the popup as Web3Auth gets instantiated. The mobile browser understands the delay in a way that the opening of the popup is caused by the website (which is blocked by default on safari ios) instead of a user driven action.

**Comment by shahbaz17** [comment] 2023-05-10 04:08
Hey @zobeirhamid 

This is fixed with our latest NoModal SDK v5.2.0.

**Closed as completed** 2023-06-13 04:47 UTC
